from enum import StrEnum


class ApplicationStatus(StrEnum):
    APPLICATION_RECEIVED = "APPLICATION_RECEIVED"
    UNDER_REVIEW = "UNDER_REVIEW"
    ASSESSMENT = "ASSESSMENT"
    INTERVIEW = "INTERVIEW"
    NEXT_ROUND = "NEXT_ROUND"
    OFFER = "OFFER"
    REJECTED = "REJECTED"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    UNKNOWN = "UNKNOWN"


TERMINAL_STATUSES = {ApplicationStatus.OFFER, ApplicationStatus.REJECTED}
